### ISSUE TITLE
Issue #3: JavaFX

### ISSUE THREAD

**Issue by tatjanarusso** [tatjanarusso/CriminalRecords#3]
JavaFX wurde installiert und konfiguriert hat jedoch einen Fehler wegen der Hauptklasse.
Fehlermeldung:
**Fehler: Hauptklasse Files\Java\javafx-sdk-17.0.0.1\lib konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: Files\Java\javafx-sdk-17.0.0.1\lib**

**Comment by janloeliger** [comment]
Problem resolved, build settings changed
